controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

HomePage:
    path: /
    controller: App\Controller\HomePageController::index

login:
    path: /login
    controller: App\Controller\SecurityController::index

logout:
    path: /logout
    controller: App\Controller\SecurityController::index

register:
    path: /register
    controller: App\Controller\RegistrationController::index

mySpace:
    path: /my_space
    controller: App\Controller\MySpaceController::index