controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

HomePage:
    path: /
    controller: App\Controller\HomePageController::index

login:
    path: /login
    controller: App\Controller\LoginController::index